baseURL = 'https://alexandre.deverteuil.net/consolefonts/'
languageCode = 'en-us'
title = 'Linux Console Fonts'

[module]
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"
