---
- name: Set up the Archlinux host
  hosts: all
  tasks:

    - name: install packages
      pacman:
        name:
          - fbdump  # Provides fbdump
          - netpbm  # Provides pnmcrop
          - libpng  # Provides pnm2png
          - rsync
        state: present

    - name: copy the script
      copy:
        src: gen-fonts-images.py
        dest: /root/gen-fonts-images.py
        mode: 0755

    - name: generate fonts images
      command: openvt --wait --switch /root/gen-fonts-images.py
      args:
        creates: /root/screenshots
