---
- name: Set up the Archlinux host
  hosts: arch
  tasks:

    - name: install packages
      pacman:
        name:
          - fbdump  # Provides fbdump
          - netpbm  # Provides pnmcrop
          - libpng  # Provides pnm2png
          - rsync
        state: present
        update_cache: yes

    - name: copy the scripts
      copy:
        src: '{{ item }}'
        dest: /root/{{ item }}
        mode: 0755
      with_items:
        - gen-fonts-images.py
        - gen-fonts-data.py

    - name: generate fonts images
      command: openvt --wait --switch /root/gen-fonts-images.py
      args:
        creates: /root/consolefonts-screenshots

    - name: generate fonts data
      command: /root/gen-fonts-data.py
      args:
        creates: /root/fonts.yaml

    - name: create compressed archive of fonts screenshots
      archive:
        path: /root/consolefonts-screenshots
        dest: /root/consolefonts-screenshots.tar.gz

    - name: download screenshots
      synchronize:
        mode: pull
        recursive: yes
        delete: yes
        src: /root/consolefonts-screenshots/
        dest: ../hugo-site/static/screenshots/

    - name: download screenshots data
      synchronize:
        mode: pull
        src: /root/fonts.yaml
        dest: ../hugo-site/data/fonts.yaml

    - name: download consolefonts-screenshots.tar.gz
      synchronize:
        mode: pull
        src: /root/consolefonts-screenshots.tar.gz
        dest: ../hugo-site/static/files/consolefonts-screenshots.tar.gz

    - name: download readme files
      synchronize:
        mode: pull
        src: /usr/share/kbd/consolefonts/
        dest: ../hugo-site/static/files/readme/
        recursive: yes
        delete: yes
        rsync_opts:
          - --filter=- partialfonts/
          - --filter=- *.gz
